server:
  port: 7529
  servlet:
    context-path: /api
spring:
  config:
    activate:
      on-profile: prod
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxxxxxxxxxxxxxxxxxx
    password: xxxxxxxxxxxxxxxxxxx
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # Redis 配置
  # todo 需替换配置
  redis:
    host: xxxxxxxxxxxxxxxxx
    port: xxxxxxxxxxxxxxx
    database: xxxxxxxxxxxx
    timeout: xxxxxxxxxxxx
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: ''
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
aliyun:
  oss:
    endpoint: xxxxxxxxxxxxxxxx
    accessKeyId: xxxxxxxxxxxxxxxxxxxxx
    accessKeySecret: xxxxxxxxxxxxxxxxxxxx
    bucketName: xxxxxxxxxxxxxxxxxx
tomato:
  gateway:
    host: xxxxxxxxxxxxxxxxxx
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://xxxxxxxxxxxxxxxxx